version: '3'

services:

  mysqldb:
   image: mysql:5.7
   container_name: inspect_db
   ports:
    - "3308:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=inspect_db
   networks: ['stack']


  app:
   image: building_inspection
   build:
     context: .
     dockerfile: docker/dev/Dockerfile
   container_name: inspect_app
   volumes:
     - .:/inspection
   ports:
     - "9000:8000"
   depends_on:
     - mysqldb
   environment:
     - STAGE=dev
   networks: ['stack']
   command: sh docker/dev/start_script.sh 1




networks:
  stack:
    driver: bridge
