# Generated by Django 3.0.8 on 2020-07-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200730_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
